### PR TITLE
Local provisioning AWS

### PR DESCRIPTION
**Pull request by Halama**
FIXES: https://keboola.atlassian.net/browse/ST-2059

 - Prepared local provisioning  
 - It creates https://keboola.atlassian.net/wiki/spaces/ENGG/pages/3527147526/GCP+Snowflake+Writer+component+with+S3+credentials#S3 :
    -  AWS IAM user for the component
    - AWS S3 bucket for component staging
    - AWS IAM role with access to created staging bucket
    - It allow to assume app user role with access to staging buckets (These temporary credentials scoped to path will be forwarded to SNFLK COPY commands) 
       - https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_assume_role.html#assuming-an-iam-role-in-another-aws-account 
       - We wil call it in app with `Policy` param scoping it to desired path in S3 https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sts-2011-06-15.html#assumerole 
       -  https://docs.snowflake.com/en/user-guide/data-load-s3-config-storage-integration#aws-access-control-requirements. 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:GetObject",
              "s3:GetObjectVersion",
              "s3:DeleteObject",
              "s3:DeleteObjectVersion"
            ],
            "Resource": "arn:aws:s3:::<bucket>/<prefix>/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::<bucket>",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "<prefix>/*"
                    ]
                }
            }
        }
    ]
}
```
 

### Manual test of deployed resources

test-read-policy.json
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:GetObjectVersion"
      ],
      "Resource": "arn:aws:s3:::martinh-snowflake-writer-gcs-s3-stagi20240809081219866100000001/export-abc/*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::martinh-snowflake-writer-gcs-s3-stagi20240809081219866100000001",
      "Condition": {
        "StringLike": {
          "s3:prefix": [
            "export-abc/*"
          ]
        }
      }
    }
  ]
}
```

test.sh
```
output=$(aws sts assume-role --role-arn $AWS_STAGING_S3_ROLE_ARN --role-session-name s3-staging-write --policy file://test-read-policy.json)

# Extract the temporary credentials from the output
AWS_ACCESS_KEY_ID=$(echo $output | jq -r '.Credentials.AccessKeyId')
AWS_SECRET_ACCESS_KEY=$(echo $output | jq -r '.Credentials.SecretAccessKey')
AWS_SESSION_TOKEN=$(echo $output | jq -r '.Credentials.SessionToken')

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

aws s3 ls $AWS_STAGING_S3_BUCKET/export-abc/
```
Run test:
```
source .env.local
sh test.sh

```

### CODE REVIEW

**Review by romantmb — CHANGES_REQUESTED** [review]
`.gitignore` a `README` můžeš klidně přepsat těmi svými, já to pak doplním.

**Review by odinuv — DISMISSED** [review]
vypadá to ok

**Comment by ujovlado** [comment]
@romantmb @Halama  tu este na nieco cakame?

**Comment by Halama** [comment]
To si @romantmb uz muze zamergovat jak chce.

**Pull request merged**
